# **Conceitos Iniciais**

In [1]:
# Libs
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import pandas as pd
import sentence_transformers
from sentence_transformers import SentenceTransformer
import tensorflow as tf
import torch

## Escalares

In [ ]:
scalar = np.array(8)

In [ ]:
print(scalar)

8


In [ ]:
type(scalar), scalar.ndim

(numpy.ndarray, 0)

## Vetores

In [ ]:
lista = [1, 2, 3]

In [ ]:
print(lista)

[1, 2, 3]


In [ ]:
type(lista)

list

In [ ]:
lista * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
vector = np.array(lista)

In [ ]:
print(vector)

[1 2 3]


In [ ]:
type(vector), vector.ndim

(numpy.ndarray, 1)

In [ ]:
vector * 2

array([2, 4, 6])

## Matriz

In [ ]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
matrix.ndim

2

In [ ]:
matrix[1][2]

np.int64(6)

In [ ]:
matrix * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

## Tensores

In [ ]:
tensor_np = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [ ]:
print(tensor_np)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [20]:
type(tensor_np)

numpy.ndarray

In [ ]:
tensor_np.ndim

3

In [ ]:
tensor_np * 2

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[14, 16, 18],
        [20, 22, 24]]])

In [ ]:
tensor_tf = tf.convert_to_tensor(tensor_np)
print(tensor_tf)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int64)


In [ ]:
type(tensor_tf)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
tensor_tf.ndim

3

In [26]:
tensor_tf * 2

<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[14, 16, 18],
        [20, 22, 24]]])>

In [27]:
tensor_pt = torch.tensor(tensor_np)
print(tensor_pt)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [28]:
type(tensor_pt)

torch.Tensor

In [29]:
tensor_pt.ndim

3

In [30]:
tensor_pt * 2

tensor([[[ 2,  4,  6],
         [ 8, 10, 12]],

        [[14, 16, 18],
         [20, 22, 24]]])