# **Matrizes**

In [1]:
import numpy as np
import scipy

## Normas

In [2]:
matrix = np.array([
    [1, 1, 2, 2, 10, 127.35],
    [2, 2, 2, 1, 10, 128.10],
    [2, 1, 2, 2, 10, 134.85],
    [2, 1, 2, 1, 10, 119.85],
])

In [3]:
matrix.ndim

2

In [4]:
matrix.shape

(4, 6)

In [5]:
matrix.size

24

In [ ]:
np.linalg.norm(matrix)

np.float64(256.16826013384247)

In [7]:
np.linalg.norm(matrix, ord=2)

np.float64(256.16224823752526)

## Matriz transposta

In [8]:
matrix

array([[  1.  ,   1.  ,   2.  ,   2.  ,  10.  , 127.35],
       [  2.  ,   2.  ,   2.  ,   1.  ,  10.  , 128.1 ],
       [  2.  ,   1.  ,   2.  ,   2.  ,  10.  , 134.85],
       [  2.  ,   1.  ,   2.  ,   1.  ,  10.  , 119.85]])

In [9]:
np.transpose(matrix)

array([[  1.  ,   2.  ,   2.  ,   2.  ],
       [  1.  ,   2.  ,   1.  ,   1.  ],
       [  2.  ,   2.  ,   2.  ,   2.  ],
       [  2.  ,   1.  ,   2.  ,   1.  ],
       [ 10.  ,  10.  ,  10.  ,  10.  ],
       [127.35, 128.1 , 134.85, 119.85]])

In [10]:
matrix.T

array([[  1.  ,   2.  ,   2.  ,   2.  ],
       [  1.  ,   2.  ,   1.  ,   1.  ],
       [  2.  ,   2.  ,   2.  ,   2.  ],
       [  2.  ,   1.  ,   2.  ,   1.  ],
       [ 10.  ,  10.  ,  10.  ,  10.  ],
       [127.35, 128.1 , 134.85, 119.85]])

## Matriz simétrica

In [11]:
sym_matrix = np.array([
    [1, 3, 2, 5],
    [3, 2, 8, 1],
    [2, 8, 6, 7],
    [5, 1, 7, 4],
])

In [12]:
scipy.linalg.issymmetric(sym_matrix)

True

In [14]:
np.all(sym_matrix == sym_matrix.T)

np.True_

## Matriz diagonal

In [15]:
diag_matrix = np.array([
    [1, 0, 0, 0],
    [0, 2, 0, 0],
    [0, 0, 6, 0],
    [0, 0, 0, 4]
])

In [16]:
diagonal_elements = np.diag(diag_matrix)
diagonal_elements

array([1, 2, 6, 4])

In [17]:
new_diag_matrix = np.diag(diagonal_elements)
new_diag_matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 4]])

In [18]:
np.all(diag_matrix == new_diag_matrix)

np.True_

In [19]:
diagonal_elements_reciprocal = np.reciprocal(diagonal_elements.astype(float))
diagonal_elements_reciprocal

array([1.        , 0.5       , 0.16666667, 0.25      ])

In [20]:
diag_matrix_inverse = np.linalg.inv(diag_matrix)
diag_matrix_inverse

array([[1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        , 0.        ],
       [0.        , 0.        , 0.16666667, 0.        ],
       [0.        , 0.        , 0.        , 0.25      ]])

In [22]:
np.all(diagonal_elements_reciprocal == np.diag(diag_matrix_inverse))

np.True_

## Matriz identidade

In [23]:
np.identity(n=4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.all(np.diag(np.identity(n=4) == 1))

np.True_

## Matriz inversa

In [25]:
sym_matrix

array([[1, 3, 2, 5],
       [3, 2, 8, 1],
       [2, 8, 6, 7],
       [5, 1, 7, 4]])

In [26]:
sym_matrix_inv = np.linalg.inv(sym_matrix)
sym_matrix_inv

array([[-0.92165899, -0.57603687,  0.41935484,  0.56221198],
       [-0.57603687, -0.23502304,  0.38709677,  0.10138249],
       [ 0.41935484,  0.38709677, -0.22580645, -0.22580645],
       [ 0.56221198,  0.10138249, -0.22580645, -0.08294931]])

In [27]:
np.dot(sym_matrix, sym_matrix_inv)

array([[ 1.00000000e+00,  1.24900090e-16,  8.32667268e-17,
         2.77555756e-17],
       [ 1.44328993e-15,  1.00000000e+00, -6.93889390e-16,
        -4.16333634e-16],
       [ 7.77156117e-16,  4.16333634e-17,  1.00000000e+00,
        -1.38777878e-16],
       [ 0.00000000e+00, -2.77555756e-16,  3.33066907e-16,
         1.00000000e+00]])

In [29]:
np.allclose(np.dot(sym_matrix, sym_matrix_inv), np.identity(4))

True

In [30]:
sing_matrix = np.array([
    [1, 3, 2, 5],
    [3, 2, 8, 1],
    [2, 6, 4, 10],
    [5, 1, 7, 4],
])

In [31]:
np.linalg.inv(sing_matrix)

LinAlgError: Singular matrix

In [32]:
sing_matrix_inv = np.linalg.pinv(sing_matrix)
sing_matrix_inv

array([[-0.02134168, -0.14181439, -0.04268335,  0.22419187],
       [ 0.03524505,  0.16579771,  0.07049009, -0.21063608],
       [-0.00389294,  0.15328467, -0.00778589, -0.04379562],
       [ 0.02467848, -0.13242961,  0.04935697,  0.09906152]])

In [33]:
matrix

array([[  1.  ,   1.  ,   2.  ,   2.  ,  10.  , 127.35],
       [  2.  ,   2.  ,   2.  ,   1.  ,  10.  , 128.1 ],
       [  2.  ,   1.  ,   2.  ,   2.  ,  10.  , 134.85],
       [  2.  ,   1.  ,   2.  ,   1.  ,  10.  , 119.85]])

In [34]:
matrix_inv = np.linalg.pinv(matrix)
matrix_inv

array([[-0.89264595, -0.13513244,  0.63533039,  0.37824551],
       [ 0.11808946,  0.85135432, -0.40113657, -0.58392994],
       [ 0.06092331, -0.04750463, -0.13399241,  0.13683291],
       [ 0.21470811, -0.27026488,  0.27066078, -0.24350898],
       [ 0.30461655, -0.23752317, -0.66996205,  0.68416453],
       [-0.01431387,  0.01801766,  0.04862261, -0.05043273]])

In [35]:
np.dot(matrix, np.linalg.pinv(matrix)).round()

array([[ 1.,  0., -0., -0.],
       [-0.,  1., -0.,  0.],
       [-0.,  0.,  1.,  0.],
       [-0.,  0., -0.,  1.]])