# **Matrizes**

In [1]:
import numpy as np
import scipy

## Normas

In [2]:
matrix = np.array([
    [1, 1, 2, 2, 10, 127.35],
    [2, 2, 2, 1, 10, 128.10],
    [2, 1, 2, 2, 10, 134.85],
    [2, 1, 2, 1, 10, 119.85],
])

In [3]:
matrix.ndim

2

In [4]:
matrix.shape

(4, 6)

In [5]:
matrix.size

24

In [ ]:
np.linalg.norm(matrix)

np.float64(256.16826013384247)

In [7]:
np.linalg.norm(matrix, ord=2)

np.float64(256.16224823752526)

## Matriz transposta

In [8]:
matrix

array([[  1.  ,   1.  ,   2.  ,   2.  ,  10.  , 127.35],
       [  2.  ,   2.  ,   2.  ,   1.  ,  10.  , 128.1 ],
       [  2.  ,   1.  ,   2.  ,   2.  ,  10.  , 134.85],
       [  2.  ,   1.  ,   2.  ,   1.  ,  10.  , 119.85]])

In [9]:
np.transpose(matrix)

array([[  1.  ,   2.  ,   2.  ,   2.  ],
       [  1.  ,   2.  ,   1.  ,   1.  ],
       [  2.  ,   2.  ,   2.  ,   2.  ],
       [  2.  ,   1.  ,   2.  ,   1.  ],
       [ 10.  ,  10.  ,  10.  ,  10.  ],
       [127.35, 128.1 , 134.85, 119.85]])

In [10]:
matrix.T

array([[  1.  ,   2.  ,   2.  ,   2.  ],
       [  1.  ,   2.  ,   1.  ,   1.  ],
       [  2.  ,   2.  ,   2.  ,   2.  ],
       [  2.  ,   1.  ,   2.  ,   1.  ],
       [ 10.  ,  10.  ,  10.  ,  10.  ],
       [127.35, 128.1 , 134.85, 119.85]])

## Matriz simétrica

In [11]:
sym_matrix = np.array([
    [1, 3, 2, 5],
    [3, 2, 8, 1],
    [2, 8, 6, 7],
    [5, 1, 7, 4],
])

In [12]:
scipy.linalg.issymmetric(sym_matrix)

True

In [14]:
np.all(sym_matrix == sym_matrix.T)

np.True_