# **Matrizes**

In [1]:
import numpy as np
import scipy

## Normas

In [2]:
matrix = np.array([
    [1, 1, 2, 2, 10, 127.35],
    [2, 2, 2, 1, 10, 128.10],
    [2, 1, 2, 2, 10, 134.85],
    [2, 1, 2, 1, 10, 119.85],
])

In [3]:
matrix.ndim

2

In [4]:
matrix.shape

(4, 6)

In [5]:
matrix.size

24

In [ ]:
np.linalg.norm(matrix)

np.float64(256.16826013384247)

In [7]:
np.linalg.norm(matrix, ord=2)

np.float64(256.16224823752526)

## Matriz transposta

In [8]:
matrix

array([[  1.  ,   1.  ,   2.  ,   2.  ,  10.  , 127.35],
       [  2.  ,   2.  ,   2.  ,   1.  ,  10.  , 128.1 ],
       [  2.  ,   1.  ,   2.  ,   2.  ,  10.  , 134.85],
       [  2.  ,   1.  ,   2.  ,   1.  ,  10.  , 119.85]])

In [9]:
np.transpose(matrix)

array([[  1.  ,   2.  ,   2.  ,   2.  ],
       [  1.  ,   2.  ,   1.  ,   1.  ],
       [  2.  ,   2.  ,   2.  ,   2.  ],
       [  2.  ,   1.  ,   2.  ,   1.  ],
       [ 10.  ,  10.  ,  10.  ,  10.  ],
       [127.35, 128.1 , 134.85, 119.85]])

In [10]:
matrix.T

array([[  1.  ,   2.  ,   2.  ,   2.  ],
       [  1.  ,   2.  ,   1.  ,   1.  ],
       [  2.  ,   2.  ,   2.  ,   2.  ],
       [  2.  ,   1.  ,   2.  ,   1.  ],
       [ 10.  ,  10.  ,  10.  ,  10.  ],
       [127.35, 128.1 , 134.85, 119.85]])

## Matriz simétrica

In [11]:
sym_matrix = np.array([
    [1, 3, 2, 5],
    [3, 2, 8, 1],
    [2, 8, 6, 7],
    [5, 1, 7, 4],
])

In [12]:
scipy.linalg.issymmetric(sym_matrix)

True

In [14]:
np.all(sym_matrix == sym_matrix.T)

np.True_

## Matriz diagonal

In [15]:
diag_matrix = np.array([
    [1, 0, 0, 0],
    [0, 2, 0, 0],
    [0, 0, 6, 0],
    [0, 0, 0, 4]
])

In [16]:
diagonal_elements = np.diag(diag_matrix)
diagonal_elements

array([1, 2, 6, 4])

In [17]:
new_diag_matrix = np.diag(diagonal_elements)
new_diag_matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 4]])

In [18]:
np.all(diag_matrix == new_diag_matrix)

np.True_

In [19]:
diagonal_elements_reciprocal = np.reciprocal(diagonal_elements.astype(float))
diagonal_elements_reciprocal

array([1.        , 0.5       , 0.16666667, 0.25      ])

In [20]:
diag_matrix_inverse = np.linalg.inv(diag_matrix)
diag_matrix_inverse

array([[1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        , 0.        ],
       [0.        , 0.        , 0.16666667, 0.        ],
       [0.        , 0.        , 0.        , 0.25      ]])

In [22]:
np.all(diagonal_elements_reciprocal == np.diag(diag_matrix_inverse))

np.True_

## Matriz identidade

In [23]:
np.identity(n=4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.all(np.diag(np.identity(n=4) == 1))

np.True_

## Matriz inversa